import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { parseMarkdown, parseYaml, writeMarkdown } from "../core/bridge.js";
import { exists, listFilesRecursive, writeJsonAtomic } from "../core/files.js";
import { PkbError } from "../core/errors.js";
import type { JsonObject, JsonValue } from "../core/types.js";
import { initializeVault } from "../core/vault.js";
import { createInstance, manageInstance } from "../platform/lifecycleWorkflow.js";
import { RuntimeRepository } from "../runtime/repository.js";
import type { RuntimeTask, TaskResources } from "../runtime/domain.js";
import { evaluateResourceGate } from "../runtime/resourceGate.js";
import { executeTask } from "../runtime/worker.js";
import { registerDeclaredJobs } from "../runtime/jobRegistry.js";
import { evaluateScheduler } from "../runtime/scheduler.js";
import { publishRuntimeEvent } from "../runtime/triggers.js";
import { applyMigration, planMigrations, rollbackMigration } from "../core/migrations.js";
import { effectivePdfUsePolicy, pdfExtractionDecision, type CaptureEnvelope } from "../core/ingestion.js";
import { ModuleSdk } from "./sdk.js";
import { createModuleWorkflowRunner } from "./workflowRunner.js";
import type { ModuleTestCheck, ModuleTestReport } from "./types.js";
import { validateModule } from "./validator.js";

function object(value: JsonValue | undefined, code: string): JsonObject {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new PkbError(code, "Expected an object.");
  return value;
}

function requiredString(value: JsonValue | undefined, label: string): string {
  if (typeof value !== "string" || !value.trim()) throw new PkbError("MODULE_TEST_FIXTURE_INVALID", `${label} is required.`);
  return value;
}

function lookup(data: JsonObject, dotted: string): JsonValue | undefined {
  let current: JsonValue | undefined = data;
  for (const part of dotted.split(".")) {
    if (Array.isArray(current)) {
      const index = Number(part);
      if (!Number.isInteger(index) || index < 0) return undefined;
      current = current[index];
      continue;
    }
    if (!current || typeof current !== "object") return undefined;
    current = (current as JsonObject)[part];
  }
  return current;
}

function fixtureFields(manifest: JsonObject, fixture: JsonObject): JsonObject {
  const form = object(manifest.instance_form, "MODULE_TEST_MANIFEST_INVALID");
  const fields = Array.isArray(form.fields) ? form.fields : [];
  const output: JsonObject = {};
  for (const raw of fields) {
    const field = object(raw as JsonValue, "MODULE_TEST_MANIFEST_INVALID");
    const key = requiredString(field.key, "instance_form.fields[].key");
    const value = lookup(fixture, key);
    if (value !== undefined) output[key] = value;
  }
  return output;
}

function check(category: ModuleTestCheck["category"], status: ModuleTestCheck["status"], message: string, details?: JsonObject): ModuleTestCheck {
  return { category, status, message, details: details ?? null };
}

async function contentHash(root: string): Promise<string> {
  const digest = createHash("sha256");
  for (const file of (await listFilesRecursive(root)).sort()) {
    const relative = path.relative(root, file).replaceAll(path.sep, "/");
    // Test reports are generated by this runner.  Including a previous report
    // would make the module checksum depend on the last test invocation.
    if (relative === "module-test-report.json" || relative === "validation-report.json") continue;
    digest.update(relative);
    digest.update(await fs.readFile(file));
  }
  return `sha256:${digest.digest("hex")}`;
}

function gitCommit(engineRoot: string): string | null {
  try { return execFileSync("git", ["-C", engineRoot, "rev-parse", "HEAD"], { encoding: "utf8", windowsHide: true }).trim() || null; }
  catch { return null; }
}

function pythonVersion(): string | null {
  const result = spawnSync("python", ["--version"], { encoding: "utf8", windowsHide: true });
  return result.status === 0 ? (result.stdout || result.stderr).trim() || null : null;
}

function nestedValue(data: JsonObject, dotted: string): JsonValue | undefined { return lookup(data, dotted); }

function valuesEqual(left: JsonValue | undefined, right: JsonValue | undefined): boolean { return JSON.stringify(left) === JSON.stringify(right); }

function promptInvariantResult(output: JsonObject, fixture: JsonObject): { ok: boolean; errors: string[] } {
  const errors: string[] = [];
  const expectedFacts = Array.isArray(fixture.expected_facts) ? fixture.expected_facts : [];
  for (const raw of expectedFacts) {
    const fact = object(raw as JsonValue, "MODULE_TEST_PROMPT_FIXTURE_INVALID");
    const field = requiredString(fact.path, "prompt expected_facts[].path");
    if (!valuesEqual(nestedValue(output, field), fact.value)) errors.push(`fact ${field} was not preserved`);
  }
  const uncertainPaths = Array.isArray(fixture.uncertain_paths) ? fixture.uncertain_paths : [];
  for (const raw of uncertainPaths) {
    if (typeof raw !== "string") continue;
    const value = nestedValue(output, raw);
    if (!(value === null || value === undefined || value === "unknown" || (Array.isArray(value) && value.length === 0))) errors.push(`uncertain field ${raw} was made definite`);
  }
  const rendered = JSON.stringify(output);
  for (const raw of Array.isArray(fixture.forbidden_values) ? fixture.forbidden_values : []) {
    if (typeof raw === "string" && rendered.includes(raw)) errors.push(`forbidden value ${raw} was invented`);
  }
  return { ok: errors.length === 0, errors };
}

function partialPdfEnvelope(): CaptureEnvelope {
  return {
    schema_version: 3, asset_id: "ASSET-TEST-PARTIAL", capture_id: "CAP-TEST-PARTIAL", source_path: "20-Workspace/fixture.pdf",
    original_asset_ref: "20-Workspace/fixture.pdf", format: "pdf", content_hash: "sha256:fixture", sidecar_path: "90-System/State/Sidecars/fixture.json",
    capture_path: "90-System/State/Sidecars/fixture.json", extraction_cache_path: "90-System/Cache/Extractions/fixture.json", companion_note_path: "30-Knowledge/Attachments/fixture.md",
    metadata: { extraction: { status: "partial", text_available: true } }, sensitivity_class: 0, classification_state: "classified",
    access_policy: { max_representation: "full" }, policy_source: "default", legacy_read_level: null, created_at: "2026-01-01T00:00:00Z",
  };
}

interface BusinessSnapshot {
  files: Record<string, string>;
  entities: Record<string, string>;
  reviewIds: string[];
  eventIds: string[];
  operationEffects: string[];
}

/**
 * Captures the durable business effects of a fixture run. Runtime logs, task
 * attempts, plans and dashboard caches intentionally do not participate: a
 * retry is allowed to create observability records, but must not create a
 * second user-visible document, entity, review, event, or applied operation.
 */
async function businessSnapshot(vaultRoot: string): Promise<BusinessSnapshot> {
  const files: Record<string, string> = {};
  const entities: Record<string, string> = {};
  for (const root of ["20-Workspace", "30-Knowledge"]) {
    const absoluteRoot = path.join(vaultRoot, root);
    if (!(await exists(absoluteRoot))) continue;
    for (const file of await listFilesRecursive(absoluteRoot)) {
      const relative = path.relative(vaultRoot, file).replaceAll(path.sep, "/");
      files[relative] = `sha256:${createHash("sha256").update(await fs.readFile(file)).digest("hex")}`;
      if (path.extname(file).toLowerCase() === ".md") {
        try {
          const document = parseMarkdown(vaultRoot, file);
          const id = document.data.id ?? document.data.entity_id ?? document.data.record_id;
          if (typeof id === "string" && id) entities[relative] = id;
        } catch { /* A non-PKB Markdown file is still a business file, just not an entity. */ }
      }
    }
  }
  const reviewIds: string[] = [];
  const reviewsRoot = path.join(vaultRoot, "90-System", "Reviews");
  if (await exists(reviewsRoot)) {
    for (const file of await listFilesRecursive(reviewsRoot, ".md")) {
      try {
        const id = parseMarkdown(vaultRoot, file).data.review_id;
        if (typeof id === "string") reviewIds.push(id);
      } catch { /* malformed review files are caught by their own validation path */ }
    }
  }
  const repository = await RuntimeRepository.open(vaultRoot);
  let eventIds: string[] = [];
  try { eventIds = repository.listEvents(10_000).map((event) => String(event.event_id ?? "")).filter(Boolean).sort(); }
  finally { repository.close(); }
  // Plans are the durable ledger of proposed/applied operations. Unlike Run
  // history, a new plan on retry is itself a duplicate business effect.
  const plansRoot = path.join(vaultRoot, "90-System", "State", "Plans");
  const operationEffects = await exists(plansRoot)
    ? (await listFilesRecursive(plansRoot, ".json")).map((file) => path.relative(plansRoot, file).replaceAll(path.sep, "/")).sort()
    : [];
  return { files, entities, reviewIds: reviewIds.sort(), eventIds, operationEffects };
}

function snapshotsEqual(before: BusinessSnapshot, after: BusinessSnapshot): boolean {
  // A retry may create a new Run, but it must reuse the durable Operation Plan
  // instead of creating a second business operation.
  return JSON.stringify(before.files) === JSON.stringify(after.files)
    && JSON.stringify(before.entities) === JSON.stringify(after.entities)
    && JSON.stringify(before.reviewIds) === JSON.stringify(after.reviewIds)
    && JSON.stringify(before.eventIds) === JSON.stringify(after.eventIds)
    && JSON.stringify(before.operationEffects) === JSON.stringify(after.operationEffects);
}

async function readReviewsById(vaultRoot: string): Promise<Map<string, JsonObject>> {
  const output = new Map<string, JsonObject>();
  const root = path.join(vaultRoot, "90-System", "Reviews");
  if (!(await exists(root))) return output;
  for (const file of await listFilesRecursive(root, ".md")) {
    try {
      const data = parseMarkdown(vaultRoot, file).data;
      if (typeof data.review_id === "string") output.set(data.review_id, data);
    } catch { /* the validation path reports malformed review content */ }
  }
  return output;
}

async function writeFixtureCapture(vault: string, inboxPath: string, fixture: JsonObject, label: string): Promise<string> {
  const capture = object(fixture.capture, "MODULE_TEST_FIXTURE_INVALID");
  const relative = requiredString(capture.path, `${label}.capture.path`);
  const content = requiredString(capture.content, `${label}.capture.content`);
  const target = `${inboxPath}/${relative}`;
  const absolute = path.join(vault, ...target.split("/"));
  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, content, "utf8");
  return target;
}

async function seedDocuments(vault: string, rawSeeds: JsonValue | undefined): Promise<void> {
  for (const raw of Array.isArray(rawSeeds) ? rawSeeds : []) {
    const seed = object(raw as JsonValue, "MODULE_TEST_FIXTURE_INVALID");
    const target = requiredString(seed.path, "seed_documents[].path");
    if (target.split("/").includes("..") || path.isAbsolute(target)) throw new PkbError("MODULE_TEST_FIXTURE_INVALID", "Seed document paths must be Vault-relative.");
    const absolute = path.join(vault, ...target.split("/"));
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    writeMarkdown(vault, absolute, { data: object(seed.data, "MODULE_TEST_FIXTURE_INVALID"), content: typeof seed.content === "string" ? seed.content : "" });
  }
}

/**
 * Executes a declarative module fixture in an isolated, disposable Vault.
 * Codex is intentionally replaced with the fixture's schema-valid output: this
 * tests Core routing, plans, idempotency and lifecycle without needing a model.
 */
export async function testModule(engineRoot: string, moduleId: string, options: { writeReport?: boolean; moduleRoot?: string } = {}): Promise<ModuleTestReport> {
  const moduleRoot = options.moduleRoot ?? path.join(engineRoot, "modules", moduleId);
  const staticValidation = await validateModule(engineRoot, moduleRoot);
  const checks: ModuleTestCheck[] = [];
  const manifest = parseYaml(engineRoot, path.join(moduleRoot, "module.yaml"));
  const fixtureRoot = path.join(moduleRoot, "fixtures", "sample-instance");
  const contractFile = path.join(fixtureRoot, "module-test.yaml");
  const instanceFile = path.join(fixtureRoot, "instance.yaml");
  const captureFile = path.join(fixtureRoot, "capture-test.yaml");
  const maturity = String(manifest.maturity ?? "experimental");
  if (staticValidation.overall === "FAIL") {
    checks.push(check("capture", "fail", "Static validation failed; behavior tests were not started."));
    return finalize(engineRoot, moduleRoot, fixtureRoot, moduleId, manifest, staticValidation, checks, options);
  }
  if (!(await exists(instanceFile)) || !(await exists(captureFile)) || !(await exists(contractFile))) {
    checks.push(check("capture", "fail", "A Beta module requires instance.yaml, capture-test.yaml, and module-test.yaml."));
    return finalize(engineRoot, moduleRoot, fixtureRoot, moduleId, manifest, staticValidation, checks, options);
  }

  const fixtureInstance = parseYaml(moduleRoot, instanceFile);
  const fixtureCapture = parseYaml(moduleRoot, captureFile);
  const contract = object(parseYaml(moduleRoot, contractFile), "MODULE_TEST_CONTRACT_INVALID");
  const scenarios = object(contract.scenarios, "MODULE_TEST_CONTRACT_INVALID");
  const requiredScenarios = ["normal_capture", "ambiguous_capture", "permission_denied", "resource_unavailable", "repeat_execution", "paused_instance", "archived_instance"];
  const missingScenarios = requiredScenarios.filter((name) => !scenarios[name] || typeof scenarios[name] !== "object" || Array.isArray(scenarios[name]));
  if (missingScenarios.length) {
    checks.push(check("capture", "fail", `Module test contract is missing required scenarios: ${missingScenarios.join(", ")}.`));
    return finalize(engineRoot, moduleRoot, fixtureRoot, moduleId, manifest, staticValidation, checks, options);
  }
  const capture = object(fixtureCapture.capture, "MODULE_TEST_FIXTURE_INVALID");
  const captureRelative = requiredString(capture.path, "capture.path");
  const captureContent = requiredString(capture.content, "capture.content");
  const expectedOutput = requiredString(capture.expected_output, "capture.expected_output");
  const codexOutput = object(capture.codex_output, "MODULE_TEST_FIXTURE_INVALID");
  const itemId = typeof capture.item_id === "string" ? capture.item_id : "module-test-capture";
  const instanceId = requiredString(fixtureInstance.instance_id, "fixture instance_id");
  const vault = await fs.mkdtemp(path.join(os.tmpdir(), `knowledgeos-module-test-${moduleId}-`));
  try {
    await initializeVault(vault, "disabled");
    const installedPath = `90-System/Modules/Installed/${moduleId}/${String(manifest.version)}`;
    await fs.cp(moduleRoot, path.join(vault, ...installedPath.split("/")), { recursive: true });
    await writeJsonAtomic(path.join(vault, "90-System", "Modules", "installed.json"), { schema_version: 1, modules: [{ id: moduleId, version: String(manifest.version), installed_path: installedPath, status: "enabled" }] });
    await createInstance(vault, {
      module_id: moduleId, instance_id: instanceId, display_name: requiredString(fixtureInstance.display_name, "fixture display_name"),
      fields: fixtureFields(manifest, fixtureInstance),
    });
    await seedDocuments(vault, capture.seed_documents);
    const sourceFile = `${String((await instanceLocation(vault, instanceId)).inbox_path)}/${captureRelative}`;
    const sourceAbsolute = path.join(vault, ...sourceFile.split("/"));
    await fs.mkdir(path.dirname(sourceAbsolute), { recursive: true });
    await fs.writeFile(sourceAbsolute, captureContent, "utf8");

    const runner = createModuleWorkflowRunner(async () => ({ output: codexOutput, stderr: "" }));
    const first = await executeFixtureTask(vault, moduleId, instanceId, sourceFile, itemId, "first", runner);
    if (first.status !== "completed" || !(await exists(path.join(vault, ...expectedOutput.split("/"))))) {
      checks.push(check("capture", "fail", "Capture fixture did not produce its declared output.", { task_status: first.status, expected_output: expectedOutput, error: first.last_error }));
    } else {
      checks.push(check("capture", "pass", "Capture fixture produced the declared output.", { expected_output: expectedOutput }));
      if (capture.restore_source_for_repeat === true && !(await exists(sourceAbsolute))) {
        await fs.mkdir(path.dirname(sourceAbsolute), { recursive: true });
        await fs.copyFile(path.join(vault, ...expectedOutput.split("/")), sourceAbsolute);
      }
      // Restoring a moved fixture source is test setup, not a business effect
      // of the retry. Snapshot only after that setup is complete.
      const firstEffects = await businessSnapshot(vault);
      const repeat = await executeFixtureTask(vault, moduleId, instanceId, sourceFile, itemId, "repeat", runner);
      const repeatEffects = await businessSnapshot(vault);
      const idempotent = repeat.status === "completed" && snapshotsEqual(firstEffects, repeatEffects);
      checks.push(check("idempotency", idempotent ? "pass" : "fail", idempotent ? "Repeated Capture completed without a second business effect." : "Repeated Capture changed user-visible files, entities, Reviews, Events, or applied Operations.", {
        task_status: repeat.status,
        first_effects: firstEffects as unknown as JsonObject,
        repeat_effects: repeatEffects as unknown as JsonObject,
      }));
    }
    const ambiguous = object(scenarios.ambiguous_capture, "MODULE_TEST_CONTRACT_INVALID");
    const ambiguousExpected = requiredString(ambiguous.expected, "ambiguous_capture.expected");
    const ambiguousFixtureFile = path.join(moduleRoot, ...requiredString(ambiguous.fixture, "ambiguous_capture.fixture").split("/"));
    const ambiguousFixture = object(parseYaml(moduleRoot, ambiguousFixtureFile), "MODULE_TEST_AMBIGUOUS_FIXTURE_INVALID");
    const ambiguousCapture = object(ambiguousFixture.capture, "MODULE_TEST_AMBIGUOUS_FIXTURE_INVALID");
    await seedDocuments(vault, ambiguousCapture.seed_documents);
    const ambiguousSource = await writeFixtureCapture(vault, String((await instanceLocation(vault, instanceId)).inbox_path), ambiguousFixture, "ambiguous_capture");
    const ambiguousItemId = typeof ambiguousCapture.item_id === "string" ? ambiguousCapture.item_id : "module-test-ambiguous";
    const ambiguousOutput = object(ambiguousCapture.codex_output, "MODULE_TEST_AMBIGUOUS_FIXTURE_INVALID");
    const reviewsBeforeAmbiguous = await readReviewsById(vault);
    const businessBeforeAmbiguous = await businessSnapshot(vault);
    const ambiguousTask = await executeFixtureTask(vault, moduleId, instanceId, ambiguousSource, ambiguousItemId, "ambiguous", createModuleWorkflowRunner(async () => ({ output: ambiguousOutput, stderr: "" })), 1);
    const reviewsAfterAmbiguous = await readReviewsById(vault);
    const businessAfterAmbiguous = await businessSnapshot(vault);
    const newReviews = [...reviewsAfterAmbiguous.entries()].filter(([reviewId]) => !reviewsBeforeAmbiguous.has(reviewId));
    const expectedError = typeof ambiguous.expected_error_code === "string" ? ambiguous.expected_error_code : null;
    const reviewMatchesSource = newReviews.some(([, review]) => {
      const source = review.source_file ?? review.origin_source_file ?? review.item_id;
      const task = review.origin_task_id ?? review.task_id;
      const target = review.target;
      return (source === ambiguousSource || source === ambiguousItemId || source === ambiguousCapture.path)
        && (task === ambiguousTask.task_id || typeof task === "string")
        && target !== null && target !== undefined;
    });
    const noBusinessWrite = JSON.stringify(businessBeforeAmbiguous.files) === JSON.stringify(businessAfterAmbiguous.files)
      && JSON.stringify(businessBeforeAmbiguous.entities) === JSON.stringify(businessAfterAmbiguous.entities)
      && JSON.stringify(businessBeforeAmbiguous.eventIds) === JSON.stringify(businessAfterAmbiguous.eventIds)
      && JSON.stringify(businessBeforeAmbiguous.operationEffects) === JSON.stringify(businessAfterAmbiguous.operationEffects);
    const ambiguousSafe = (ambiguousExpected === "review" && ambiguousTask.status === "completed" && newReviews.length > 0 && reviewMatchesSource && noBusinessWrite)
      || (["rejected", "failed"].includes(ambiguousExpected) && ambiguousTask.status === "failed" && newReviews.length === 0 && noBusinessWrite);
    checks.push(check("ambiguous", ambiguousSafe && (!expectedError || ambiguousTask.last_error?.code === expectedError) ? "pass" : "fail",
      ambiguousSafe ? "Ambiguous Capture was actually executed and stopped before an unreviewed write." : "Ambiguous Capture did not reach its declared safe outcome.", {
        expected: ambiguousExpected, task_status: ambiguousTask.status, error: ambiguousTask.last_error,
        new_review_ids: newReviews.map(([reviewId]) => reviewId), review_matches_source: reviewMatchesSource, no_business_write: noBusinessWrite,
      }));

    const permission = object(scenarios.permission_denied, "MODULE_TEST_CONTRACT_INVALID");
    const deniedTarget = requiredString(permission.target, "permission_denied.target");
    const instance = await instanceLocation(vault, instanceId);
    const sdk = new ModuleSdk({ vaultRoot: vault, moduleId, moduleVersion: String(manifest.version), instanceId, allowedReadRoots: [requiredString(instance.content_root, "instance.content_root")], ownedWriteRoots: [requiredString(instance.content_root, "instance.content_root")], maxSensitivityClass: 0 });
    let denied = false;
    try { sdk.buildOperationPlan({ planId: "PLAN-TEST-DENIED", taskId: "TASK-TEST-DENIED", summary: "permission fixture", operations: [{ operation_id: "OP-001", type: "create-file", target: deniedTarget, risk: "green", confidence: 1, idempotency_key: "test-denied", requires_review_id: null, payload: { format: "text", text: "must not write" } }] }); }
    catch { denied = true; }
    checks.push(check("permission", denied ? "pass" : "fail", denied ? "Cross-boundary write was rejected." : "Permission fixture unexpectedly built a cross-boundary plan."));

    const resource = object(scenarios.resource_unavailable, "MODULE_TEST_CONTRACT_INVALID");
    const resourceName = requiredString(resource.resource, "resource_unavailable.resource");
    const expectedWaitingStatus = requiredString(resource.expected, "resource_unavailable.expected");
    if (resourceName !== "codex") throw new PkbError("MODULE_TEST_CONTRACT_INVALID", `Unsupported resource fixture: ${resourceName}.`);
    const resourceRepository = await RuntimeRepository.open(vault);
    let resourceGate;
    try {
      const resourceTask = resourceRepository.createTask({ job_id: `${moduleId}.fixture-resource`, module: moduleId, instance_id: instanceId, task_type: "workflow", workflow: `module:${moduleId}:capture`, priority: "high", resources: { filesystem: "required", network: "not-required", codex: "required", user: "not-required" }, trigger: { type: "manual" }, catch_up_policy: "none", idempotency_key: `module-test:${moduleId}:${instanceId}:codex-unavailable`, payload: { source_file: sourceFile, item_id: itemId } }).task;
      resourceRepository.setResourceStatus({ resource: "codex", status: "unavailable", reason: "fixture", checked_at: new Date().toISOString(), details: {} });
      resourceGate = await evaluateResourceGate(vault, resourceRepository, resourceTask);
    } finally { resourceRepository.close(); }
    checks.push(check("resource", resourceGate?.waiting_status === expectedWaitingStatus ? "pass" : "fail", resourceGate?.waiting_status === expectedWaitingStatus ? "Codex-unavailable Capture is held by the Resource Gate." : "Codex-unavailable Capture did not enter its declared waiting state.", { resource: resourceName, expected: expectedWaitingStatus, actual: resourceGate?.waiting_status ?? null }));

    const prompt = object(scenarios.prompt_regression, "MODULE_TEST_CONTRACT_INVALID");
    const invariantFile = path.join(moduleRoot, ...requiredString(prompt.fixture, "prompt_regression.fixture").split("/"));
    const promptFixture = parseYaml(moduleRoot, invariantFile);
    const invariants = Array.isArray(promptFixture.invariants) ? promptFixture.invariants.filter((item): item is string => typeof item === "string") : [];
    const requiredInvariants = ["preserve-facts", "uncertainty-preserved", "schema-valid"];
    const missingInvariants = requiredInvariants.filter((name) => !invariants.includes(name));
    if (!invariants.includes("no-invented-values") && !invariants.includes("no-invented-completion")) missingInvariants.push("no-invented-values or no-invented-completion");
    let promptOutput: JsonObject | null = null;
    try { promptOutput = parseMarkdown(vault, path.join(vault, ...expectedOutput.split("/"))).data; }
    catch { /* capture check carries the missing output failure; retain a useful regression failure too. */ }
    const invariantResult = promptOutput ? promptInvariantResult(promptOutput, promptFixture) : { ok: false, errors: ["the real Capture output was unavailable"] };
    const generated = promptOutput?.generation && typeof promptOutput.generation === "object" && !Array.isArray(promptOutput.generation)
      ? (promptOutput.generation as JsonObject).prompt : null;
    const promptWasUsed = generated && typeof generated === "object" && !Array.isArray(generated);
    checks.push(check("prompt-regression", !missingInvariants.length && invariantResult.ok && Boolean(promptWasUsed) ? "pass" : "fail",
      !missingInvariants.length && invariantResult.ok && promptWasUsed ? "Deterministic Prompt Contract Test passed: fixture output preserved its declared invariants." : `Deterministic Prompt Contract Test failed: ${[...missingInvariants, ...invariantResult.errors, ...(promptWasUsed ? [] : ["generation prompt trace is missing"])] .join(", ")}.`,
      { test_kind: "deterministic-prompt-contract", real_model_evaluation: false, invariants, invariant_errors: invariantResult.errors, prompt_trace_present: Boolean(promptWasUsed) }));

    const periodic = object(scenarios.periodic_job, "MODULE_TEST_CONTRACT_INVALID");
    if (periodic.enabled === true) {
      await registerDeclaredJobs(vault);
      const scheduledAt = new Date(requiredString(periodic.scheduled_at, "periodic_job.scheduled_at"));
      const scheduled = await evaluateScheduler(vault, scheduledAt);
      const expectedJobId = requiredString(periodic.job_id, "periodic_job.job_id");
      const repository = await RuntimeRepository.open(vault);
      let periodicTask;
      try { periodicTask = scheduled.created.map((taskId) => repository.getTask(taskId)).find((task) => task?.module === moduleId && task.job_id === expectedJobId && task.instance_id === instanceId) ?? null; }
      finally { repository.close(); }
      const periodicOutput = object(periodic.codex_output, "MODULE_TEST_CONTRACT_INVALID");
      const completed = periodicTask ? await executeExistingTask(vault, periodicTask, createModuleWorkflowRunner(async () => ({ output: periodicOutput, stderr: "" }))) : null;
      const periodicOutputPath = requiredString(periodic.expected_output, "periodic_job.expected_output");
      const periodicPassed = completed?.status === "completed" && await exists(path.join(vault, ...periodicOutputPath.split("/")));
      checks.push(check("periodic", periodicPassed ? "pass" : "fail", periodicPassed ? "The module's declared periodic Job created and completed its own Task." : "The module's declared periodic Job was not created and completed.", { expected_job_id: expectedJobId, created: scheduled.created, task_status: completed?.status ?? null, expected_output: periodicOutputPath }));
    } else checks.push(check("periodic", "not-applicable", "Module has no periodic Job scenario."));

    const event = object(scenarios.event_consumption, "MODULE_TEST_CONTRACT_INVALID");
    if (event.enabled === true) {
      await registerDeclaredJobs(vault);
      const expectedJobId = requiredString(event.job_id, "event_consumption.job_id");
      const repository = await RuntimeRepository.open(vault);
      let declaredJob = null;
      try { declaredJob = repository.listJobs().find((job) => job.job_id === expectedJobId && job.module === moduleId && job.trigger.instance_id === instanceId && job.trigger.type === "event" && job.trigger.event === requiredString(event.event_type, "event_consumption.event_type")) ?? null; }
      finally { repository.close(); }
      const published = declaredJob ? await publishRuntimeEvent(vault, { type: requiredString(event.event_type, "event_consumption.event_type"), module: moduleId, instance_id: instanceId, payload: object(event.payload, "event_consumption.payload") }) : null;
      const taskId = published?.created[0] ?? null;
      const eventRepository = await RuntimeRepository.open(vault);
      let eventTask = null;
      try { eventTask = taskId ? eventRepository.getTask(taskId) : null; }
      finally { eventRepository.close(); }
      const eventOutput = object(event.codex_output, "MODULE_TEST_CONTRACT_INVALID");
      const completed = eventTask ? await executeExistingTask(vault, eventTask, createModuleWorkflowRunner(async () => ({ output: eventOutput, stderr: "" }))) : null;
      const expectedOutput = requiredString(event.expected_output, "event_consumption.expected_output");
      const eventPassed = Boolean(declaredJob && published && eventTask?.job_id === expectedJobId && completed?.status === "completed" && await exists(path.join(vault, ...expectedOutput.split("/"))));
      checks.push(check("event", eventPassed ? "pass" : "fail", eventPassed ? "The module's declared Event subscription produced and completed its downstream Task." : "The module's declared Event subscription did not complete.", { expected_job_id: expectedJobId, created: published?.created ?? [], task_status: completed?.status ?? null }));
    } else checks.push(check("event", "not-applicable", "Module has no event-consumption scenario."));

    const publication = scenarios.event_publication && typeof scenarios.event_publication === "object" && !Array.isArray(scenarios.event_publication)
      ? scenarios.event_publication as JsonObject : null;
    if (publication?.enabled === true) {
      const eventType = requiredString(publication.event_type, "event_publication.event_type");
      let publicationTask: RuntimeTask | null = null;
      if (typeof publication.workflow_id === "string") {
        const seed = object(publication.seed, "MODULE_TEST_CONTRACT_INVALID");
        if (typeof seed.record_path === "string" && typeof seed.next_check === "string") {
          const recordPath = path.join(vault, ...seed.record_path.split("/"));
          const document = parseMarkdown(vault, recordPath);
          const monitoring = object(document.data.monitoring, "MODULE_TEST_CONTRACT_INVALID");
          monitoring.next_check = seed.next_check;
          writeMarkdown(vault, recordPath, { data: { ...document.data, monitoring }, content: document.content });
        }
        publicationTask = await executeFixtureWorkflow(vault, moduleId, publication.instance_id === null ? null : instanceId, publication.workflow_id, "event-publication", createModuleWorkflowRunner(async () => ({ output: {}, stderr: "" })));
      }
      const repository = await RuntimeRepository.open(vault);
      let publishedEvent = null;
      try { publishedEvent = repository.listEvents().find((item) => item.event_type === eventType && item.module === moduleId && item.instance_id === (publication.instance_id === null ? null : instanceId)) ?? null; }
      finally { repository.close(); }
      checks.push(check("event", publishedEvent?.status === "published" ? "pass" : "fail", publishedEvent?.status === "published" ? "The module Workflow actually published its declared Event." : "The module Workflow did not publish its declared Event.", { event_type: eventType, event_id: publishedEvent?.event_id ?? null, status: publishedEvent?.status ?? null, task_status: publicationTask?.status ?? null, task_error: publicationTask?.last_error ?? null }));
    } else checks.push(check("event", "not-applicable", "Module has no event-publication scenario."));

    const pdf = scenarios.pdf_policy && typeof scenarios.pdf_policy === "object" && !Array.isArray(scenarios.pdf_policy)
      ? scenarios.pdf_policy as JsonObject : null;
    if (pdf?.enabled === true) {
      const policy = effectivePdfUsePolicy(manifest.pdf_policy);
      const partial = pdfExtractionDecision(partialPdfEnvelope(), policy);
      const expectedPartial = typeof pdf.partial_expected === "string" ? pdf.partial_expected : policy.partial_policy;
      const passed = (expectedPartial === "allow" && partial.usable && !partial.requires_review)
        || (expectedPartial === "review" && !partial.usable && partial.requires_review);
      checks.push(check("pdf", passed ? "pass" : "fail", passed ? "PDF policy was executed against a partial extraction with the module's declared outcome." : "PDF policy did not enforce its declared partial-extraction outcome.", {
        test_kind: "deterministic-pdf-policy-execution", policy, partial_decision: partial, expected_partial: expectedPartial,
      }));
    } else checks.push(check("pdf", "not-applicable", "Module does not accept PDF input."));

    const partialPdf = scenarios.partial_pdf_execution && typeof scenarios.partial_pdf_execution === "object" && !Array.isArray(scenarios.partial_pdf_execution)
      ? scenarios.partial_pdf_execution as JsonObject : null;
    if (partialPdf?.enabled === true) {
      const decision = pdfExtractionDecision(partialPdfEnvelope(), effectivePdfUsePolicy(manifest.pdf_policy));
      checks.push(check("pdf", decision.usable ? "pass" : "fail", decision.usable ? "Partial PDF execution is allowed by the module policy." : "Partial PDF execution was declared but the resolved module policy blocks it.", {
        test_kind: "partial-pdf-execution", partial_decision: decision,
      }));
    }

    const migration = object(scenarios.migration_apply, "MODULE_TEST_CONTRACT_INVALID");
    if (migration.enabled === true) {
      const planned = (await planMigrations(vault, engineRoot)).filter((candidate) => candidate.module_id === moduleId);
      const run = planned[0];
      if (!run) checks.push(check("migration", "fail", "Migration fixture did not produce a migration plan."));
      else {
        const applied = await applyMigration(vault, run.migration_run_id);
        const repeated = await applyMigration(vault, run.migration_run_id);
        const rolledBack = applied.status === "completed" && migration.rollback === true ? await rollbackMigration(vault, run.migration_run_id) : null;
        checks.push(check("migration", applied.status === "completed" && repeated.status === "completed" && (!migration.rollback || rolledBack?.status === "rolled-back") ? "pass" : "fail", "Migration apply, repeat, and rollback completed.", { status: applied.status, repeat_status: repeated.status, rollback_status: rolledBack?.status ?? null }));
      }
    } else checks.push(check("migration", "not-applicable", "Module declares no schema migration."));
    try {
      await manageInstance(vault, { instance_id: instanceId, action: "pause" });
      await registerDeclaredJobs(vault);
      const pausedRepository = await RuntimeRepository.open(vault);
      let pausedJobs;
      try { pausedJobs = pausedRepository.listJobs().filter((job) => job.module === moduleId && job.scope === "instance" && !job.job_id.includes(".fixture-event.")); }
      finally { pausedRepository.close(); }
      checks.push(check("lifecycle", pausedJobs.every((job) => !job.enabled) ? "pass" : "fail", pausedJobs.every((job) => !job.enabled) ? "Paused instance disabled its periodic Jobs." : "Paused instance left periodic Jobs enabled."));
      await manageInstance(vault, { instance_id: instanceId, action: "resume" });
      await manageInstance(vault, { instance_id: instanceId, action: "archive", confirm: true });
      await registerDeclaredJobs(vault);
      const archivedRepository = await RuntimeRepository.open(vault);
      let archivedJobs;
      try { archivedJobs = archivedRepository.listJobs().filter((job) => job.module === moduleId && job.scope === "instance"); }
      finally { archivedRepository.close(); }
      const archiveSafe = archivedJobs.every((job) => !job.enabled);
      checks.push(check("lifecycle", archiveSafe ? "pass" : "fail", archiveSafe ? "Archived instance disabled its declared Jobs." : "Archived instance left declared Jobs enabled."));
    } catch (error) {
      checks.push(check("lifecycle", "fail", error instanceof Error ? error.message : String(error)));
    }
  } catch (error) {
    checks.push(check("capture", "fail", error instanceof Error ? error.message : String(error)));
  } finally { await fs.rm(vault, { recursive: true, force: true }); }
  return finalize(engineRoot, moduleRoot, fixtureRoot, moduleId, manifest, staticValidation, checks, options);
}

async function instanceLocation(vaultRoot: string, instanceId: string): Promise<JsonObject> {
  return parseYaml(vaultRoot, path.join(vaultRoot, "90-System", "Instances", instanceId, "instance.yaml"));
}

async function executeFixtureTask(vaultRoot: string, moduleId: string, instanceId: string, sourceFile: string, itemId: string, attempt: string, runner: ReturnType<typeof createModuleWorkflowRunner>, maxAttempts = 3, resources: Record<keyof TaskResources, "available" | "unavailable" | "not-required"> = { filesystem: "available", network: "not-required", codex: "available", user: "available" }) {
  const repository = await RuntimeRepository.open(vaultRoot);
  try {
    const task = repository.createTask({
      job_id: `${moduleId}.fixture-capture`, module: moduleId, instance_id: instanceId, task_type: "workflow", workflow: `module:${moduleId}:capture`, priority: "high",
      resources: { filesystem: "required", network: "not-required", codex: "required", user: "not-required" },
      trigger: { type: "manual", entrypoint: "capture" }, catch_up_policy: "none", idempotency_key: `module-test:${moduleId}:${instanceId}:${itemId}:${attempt}`,
      max_attempts: maxAttempts, payload: { source_file: sourceFile, item_id: itemId },
    }).task;
    return await executeTask(vaultRoot, repository, task, "module-test-runner", resources, {}, runner);
  } finally { repository.close(); }
}

async function executeExistingTask(vaultRoot: string, task: RuntimeTask, runner: ReturnType<typeof createModuleWorkflowRunner>) {
  const repository = await RuntimeRepository.open(vaultRoot);
  try {
    return await executeTask(vaultRoot, repository, task, "module-test-runner", { filesystem: "available", network: "not-required", codex: "available", user: "available" }, {}, runner);
  } finally { repository.close(); }
}

async function executeFixtureWorkflow(vaultRoot: string, moduleId: string, instanceId: string | null, workflowId: string, suffix: string, runner: ReturnType<typeof createModuleWorkflowRunner>): Promise<RuntimeTask> {
  const repository = await RuntimeRepository.open(vaultRoot);
  try {
    const task = repository.createTask({
      job_id: `${moduleId}.fixture-${suffix}`, module: moduleId, instance_id: instanceId, task_type: "workflow", workflow: `${moduleId}:${workflowId}`, priority: "high",
      resources: { filesystem: "required", network: "not-required", codex: "not-required", user: "not-required" },
      trigger: { type: "manual", entrypoint: workflowId }, catch_up_policy: "none", idempotency_key: `module-test:${moduleId}:${instanceId ?? "module"}:${suffix}:${workflowId}`,
      payload: {},
    }).task;
    return await executeTask(vaultRoot, repository, task, "module-test-runner", { filesystem: "available", network: "not-required", codex: "available", user: "available" }, {}, runner);
  } finally { repository.close(); }
}

async function finalize(engineRoot: string, moduleRoot: string, fixtureRoot: string, moduleId: string, manifest: JsonObject, staticValidation: Awaited<ReturnType<typeof validateModule>>, checks: ModuleTestCheck[], options: { writeReport?: boolean }): Promise<ModuleTestReport> {
  const capturePassed = checks.some((item) => item.category === "capture" && item.status === "pass");
  const failed = staticValidation.overall === "FAIL" || checks.some((item) => item.status === "fail");
  let engineVersion = "unknown";
  try { engineVersion = String((JSON.parse(await fs.readFile(path.join(engineRoot, "package.json"), "utf8")) as { version?: string }).version ?? "unknown"); }
  catch { /* The report remains reproducible even for a partial source checkout. */ }
  const report: ModuleTestReport = {
    report_version: 1, module_id: moduleId, module_version: String(manifest.version), generated_at: new Date().toISOString(), static_validation: staticValidation,
    environment: {
      git_commit: gitCommit(engineRoot), engine_version: engineVersion, module_checksum: await contentHash(moduleRoot),
      fixture_checksum: await exists(fixtureRoot) ? await contentHash(fixtureRoot) : "missing",
      os: `${os.platform()} ${os.release()}`, node: process.version, python: pythonVersion(),
    },
    checks, overall: failed ? "FAIL" : "PASS", beta_eligible: !failed && (String(manifest.maturity) !== "beta" || capturePassed),
  };
  if (options.writeReport) await writeJsonAtomic(path.join(moduleRoot, "module-test-report.json"), report);
  return report;
}
